CREATE TABLE user_activity_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at timestamp NOT NULL,
    action_type varchar(80) NOT NULL,
    description varchar(1000) NOT NULL,
    actor_id bigint NOT NULL REFERENCES person(id) ON DELETE CASCADE
);

CREATE INDEX idx_user_activity_log_actor_time ON user_activity_log (actor_id, occurred_at DESC);
CREATE INDEX idx_user_activity_log_action_type ON user_activity_log (action_type);
