DROP TRIGGER trg_active_semester_subject_has_teacher ON semester_subject;
DROP TRIGGER trg_class_meeting_semester_subject ON class_meeting;
DROP TRIGGER trg_weekly_schedule_group_semester ON weekly_schedule_entry;
DROP TRIGGER trg_weekly_schedule_semester_subject ON weekly_schedule_entry;

CREATE TABLE semester_field (
    semester_id bigint NOT NULL REFERENCES semester(id) ON DELETE CASCADE,
    field_id bigint NOT NULL REFERENCES field_of_study(id),
    PRIMARY KEY (semester_id, field_id)
);

INSERT INTO semester_field (semester_id, field_id)
SELECT id, field_id
FROM semester;

ALTER TABLE student_group
    ADD COLUMN field_id bigint;

UPDATE student_group g
SET field_id = sem.field_id
FROM semester sem
WHERE sem.id = g.semester_id;

ALTER TABLE student_group
    ALTER COLUMN field_id SET NOT NULL,
    ADD CONSTRAINT uk_student_group_academic_context UNIQUE (id, semester_id, field_id),
    ADD CONSTRAINT fk_student_group_semester_field
        FOREIGN KEY (semester_id, field_id)
        REFERENCES semester_field (semester_id, field_id)
        DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE weekly_schedule_entry
    ADD COLUMN field_id bigint;

UPDATE weekly_schedule_entry w
SET field_id = sem.field_id
FROM semester sem
WHERE sem.id = w.semester_id;

ALTER TABLE weekly_schedule_entry
    ALTER COLUMN field_id SET NOT NULL,
    ADD CONSTRAINT fk_weekly_schedule_group_context
        FOREIGN KEY (group_id, semester_id, field_id)
        REFERENCES student_group (id, semester_id, field_id)
        DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE semester_field_subject (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semester_id bigint NOT NULL,
    field_id bigint NOT NULL,
    subject_id bigint NOT NULL REFERENCES subject(id) ON DELETE CASCADE,
    CONSTRAINT uk_semester_field_subject UNIQUE (semester_id, field_id, subject_id),
    CONSTRAINT fk_curriculum_semester_field
        FOREIGN KEY (semester_id, field_id)
        REFERENCES semester_field (semester_id, field_id)
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED
);

INSERT INTO semester_field_subject (semester_id, field_id, subject_id)
SELECT ss.semester_id, sem.field_id, ss.subject_id
FROM semester_subject ss
JOIN semester sem ON sem.id = ss.semester_id;

DROP TABLE semester_subject;

ALTER TABLE semester
    DROP COLUMN field_id;

CREATE INDEX idx_semester_field_field_id
    ON semester_field (field_id, semester_id);
CREATE INDEX idx_student_group_field_semester
    ON student_group (field_id, semester_id);
CREATE INDEX idx_curriculum_subject
    ON semester_field_subject (subject_id, semester_id, field_id);
CREATE INDEX idx_curriculum_field_semester
    ON semester_field_subject (field_id, semester_id);
CREATE INDEX idx_weekly_schedule_academic_context
    ON weekly_schedule_entry (semester_id, field_id, group_id);

CREATE OR REPLACE FUNCTION validate_class_meeting_semester_subject()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM student_group g
        JOIN semester_field_subject curriculum
          ON curriculum.semester_id = g.semester_id
         AND curriculum.field_id = g.field_id
        WHERE g.id = NEW.group_id
          AND curriculum.subject_id = NEW.subject_id
    ) THEN
        RAISE EXCEPTION
            'Subject % is not available for the selected group semester and field',
            NEW.subject_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION validate_weekly_schedule_group_semester()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM student_group g
        WHERE g.id = NEW.group_id
          AND g.semester_id = NEW.semester_id
          AND g.field_id = NEW.field_id
    ) THEN
        RAISE EXCEPTION
            'Weekly schedule semester and field must match the selected group';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION validate_weekly_schedule_semester_subject()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM semester_field_subject curriculum
        WHERE curriculum.semester_id = NEW.semester_id
          AND curriculum.field_id = NEW.field_id
          AND curriculum.subject_id = NEW.subject_id
    ) THEN
        RAISE EXCEPTION
            'Subject % is not available in semester % and field %',
            NEW.subject_id, NEW.semester_id, NEW.field_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION validate_group_subject_curriculum()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM student_group g
        JOIN semester_field_subject curriculum
          ON curriculum.semester_id = g.semester_id
         AND curriculum.field_id = g.field_id
        WHERE g.id = NEW.group_id
          AND curriculum.subject_id = NEW.subject_id
    ) THEN
        RAISE EXCEPTION
            'Subject % is not available for group % semester and field',
            NEW.subject_id, NEW.group_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION validate_group_academic_context_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM subject_group sg
        WHERE sg.group_id = NEW.id
          AND NOT EXISTS (
              SELECT 1
              FROM semester_field_subject curriculum
              WHERE curriculum.semester_id = NEW.semester_id
                AND curriculum.field_id = NEW.field_id
                AND curriculum.subject_id = sg.subject_id
          )
    ) THEN
        RAISE EXCEPTION
            'Group % has subjects outside its new semester and field curriculum',
            NEW.id;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM class_meeting cm
        JOIN semester sem ON sem.id = NEW.semester_id
        WHERE cm.group_id = NEW.id
          AND (
              sem.start_date IS NOT NULL AND cm.meeting_date < sem.start_date
              OR sem.end_date IS NOT NULL AND cm.meeting_date > sem.end_date
          )
    ) THEN
        RAISE EXCEPTION
            'Group % has class meetings outside its new semester period',
            NEW.id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION protect_used_curriculum_assignment()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM subject_group sg
        JOIN student_group g ON g.id = sg.group_id
        WHERE g.semester_id = OLD.semester_id
          AND g.field_id = OLD.field_id
          AND sg.subject_id = OLD.subject_id
    ) OR EXISTS (
        SELECT 1
        FROM weekly_schedule_entry w
        WHERE w.semester_id = OLD.semester_id
          AND w.field_id = OLD.field_id
          AND w.subject_id = OLD.subject_id
    ) THEN
        RAISE EXCEPTION
            'Cannot remove curriculum subject % while it is used in semester % and field %',
            OLD.subject_id, OLD.semester_id, OLD.field_id;
    END IF;
    RETURN OLD;
END;
$$;

CREATE OR REPLACE FUNCTION validate_semester_has_field()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    checked_semester_id bigint;
BEGIN
    IF TG_TABLE_NAME = 'semester' THEN
        checked_semester_id := NEW.id;
    ELSIF TG_OP = 'DELETE' THEN
        checked_semester_id := OLD.semester_id;
    ELSE
        checked_semester_id := NEW.semester_id;
    END IF;

    IF EXISTS (SELECT 1 FROM semester WHERE id = checked_semester_id)
       AND NOT EXISTS (
           SELECT 1
           FROM semester_field
           WHERE semester_id = checked_semester_id
       ) THEN
        RAISE EXCEPTION
            'Semester % must belong to at least one field of study',
            checked_semester_id;
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION validate_active_subject_has_teacher()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    subject_to_check bigint;
    teacher_count integer;
    active_count integer;
BEGIN
    IF TG_TABLE_NAME = 'teacher_subject'
       AND TG_OP = 'UPDATE'
       AND OLD.subject_id IS DISTINCT FROM NEW.subject_id THEN
        subject_to_check := OLD.subject_id;

        SELECT COUNT(*)
        INTO active_count
        FROM (
            SELECT subject_id
            FROM semester_field_subject
            WHERE subject_id = subject_to_check
            UNION ALL
            SELECT subject_id
            FROM subject_group
            WHERE subject_id = subject_to_check
        ) active_subject;

        IF active_count > 0 THEN
            SELECT COUNT(*)
            INTO teacher_count
            FROM teacher_subject
            WHERE subject_id = subject_to_check;

            IF teacher_count < 1 THEN
                RAISE EXCEPTION
                    'Active subject % must have at least one qualified teacher',
                    subject_to_check;
            END IF;
        END IF;
    END IF;

    IF TG_OP = 'DELETE' THEN
        subject_to_check := OLD.subject_id;
    ELSE
        subject_to_check := NEW.subject_id;
    END IF;

    SELECT COUNT(*)
    INTO active_count
    FROM (
        SELECT subject_id
        FROM semester_field_subject
        WHERE subject_id = subject_to_check
        UNION ALL
        SELECT subject_id
        FROM subject_group
        WHERE subject_id = subject_to_check
    ) active_subject;

    IF active_count > 0 THEN
        SELECT COUNT(*)
        INTO teacher_count
        FROM teacher_subject
        WHERE subject_id = subject_to_check;

        IF teacher_count < 1 THEN
            RAISE EXCEPTION
                'Active subject % must have at least one qualified teacher',
                subject_to_check;
        END IF;
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_semester_has_field_from_semester
AFTER INSERT ON semester
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION validate_semester_has_field();

CREATE CONSTRAINT TRIGGER trg_semester_has_field_from_link
AFTER UPDATE OR DELETE ON semester_field
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION validate_semester_has_field();

CREATE CONSTRAINT TRIGGER trg_group_subject_curriculum
AFTER INSERT OR UPDATE OF subject_id, group_id ON subject_group
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION validate_group_subject_curriculum();

CREATE CONSTRAINT TRIGGER trg_group_academic_context_update
AFTER UPDATE OF semester_id, field_id ON student_group
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION validate_group_academic_context_update();

CREATE CONSTRAINT TRIGGER trg_protect_used_curriculum_assignment
AFTER DELETE ON semester_field_subject
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION protect_used_curriculum_assignment();

CREATE CONSTRAINT TRIGGER trg_class_meeting_semester_subject
AFTER INSERT OR UPDATE OF subject_id, group_id ON class_meeting
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION validate_class_meeting_semester_subject();

CREATE CONSTRAINT TRIGGER trg_weekly_schedule_group_semester
AFTER INSERT OR UPDATE OF group_id, semester_id, field_id ON weekly_schedule_entry
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION validate_weekly_schedule_group_semester();

CREATE CONSTRAINT TRIGGER trg_weekly_schedule_semester_subject
AFTER INSERT OR UPDATE OF subject_id, semester_id, field_id ON weekly_schedule_entry
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION validate_weekly_schedule_semester_subject();

CREATE CONSTRAINT TRIGGER trg_active_semester_field_subject_has_teacher
AFTER INSERT OR UPDATE OF subject_id ON semester_field_subject
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION validate_active_subject_has_teacher();
